# ecdna-bench Makefile
# Run `make help` for a list of targets.

PYTHON      ?= python
CONFIG      ?= configs/default.yaml
LOG_LEVEL   ?= INFO

.PHONY: help install test lint benchmark clean notebooks \
        build-metadata run-qc optimize-classical run-classical \
        train-eccount run-eccount run-baselines sensitivity \
        eval-only all-from-scratch

# ────────────────────────────────────────────────────────────────────────────
help:
	@echo ""
	@echo "ecdna-bench — available targets"
	@echo "────────────────────────────────────────────────────────────────"
	@echo "  install            pip install -e . (editable install)"
	@echo "  test               run pytest (126 tests)"
	@echo "  lint               ruff + mypy"
	@echo ""
	@echo "  build-metadata     build metadata.csv + counts_master.csv"
	@echo "  run-qc             file audit + count-mask consistency"
	@echo "  optimize-classical 3-stage Bayesian optimisation"
	@echo "  run-classical      classical inference → binary masks"
	@echo "  train-eccount      train ecCount U-Net"
	@echo "  run-eccount        ecCount inference → threshold + peaks masks"
	@echo "  run-baselines      harmonise ecSeg + MIA + Label Engine"
	@echo "  benchmark          full cross-model benchmark evaluation"
	@echo "  sensitivity        d_max × IoU_min sensitivity sweep"
	@echo "  notebooks          how to regenerate the paper figures"
	@echo ""
	@echo "  clean              remove __pycache__ and .tmp files"
	@echo "────────────────────────────────────────────────────────────────"
	@echo ""

# ────────────────────────────────────────────────────────────────────────────
install:
	pip install -e .

test:
	$(PYTHON) -m pytest tests/ -q --tb=short

lint:
	$(PYTHON) -m ruff check src/ tests/
	$(PYTHON) -m mypy src/ecdna_bench --ignore-missing-imports

# ────────────────────────────────────────────────────────────────────────────
# Pipeline stages
# ────────────────────────────────────────────────────────────────────────────

build-metadata:
	$(PYTHON) -m ecdna_bench.cli.build_metadata \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

run-qc:
	$(PYTHON) -m ecdna_bench.cli.run_qc \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

optimize-classical:
	$(PYTHON) -m ecdna_bench.cli.optimize_classical \
	    --stage all \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

run-classical:
	$(PYTHON) -m ecdna_bench.cli.run_classical \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

train-eccount:
	$(PYTHON) -m ecdna_bench.cli.train_eccount \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

run-eccount:
	$(PYTHON) -m ecdna_bench.cli.run_eccount \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

run-baselines:
	$(PYTHON) -m ecdna_bench.cli.run_baseline --model ecseg        --config $(CONFIG)
	$(PYTHON) -m ecdna_bench.cli.run_baseline --model mia          --config $(CONFIG)
	$(PYTHON) -m ecdna_bench.cli.run_baseline --model label_engine --config $(CONFIG)

benchmark:
	$(PYTHON) -m ecdna_bench.cli.benchmark \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

sensitivity:
	$(PYTHON) -m ecdna_bench.cli.sensitivity \
	    --config $(CONFIG) \
	    --log-level $(LOG_LEVEL)

# Figures are produced by the notebooks, not a CLI command.
notebooks:
	@echo "Figures are regenerated by running the notebooks in order:"
	@echo "  notebooks/01_dataset_exploration.ipynb"
	@echo "  notebooks/02_classical_pipeline.ipynb"
	@echo "  notebooks/03_models_comparison.ipynb"
	@echo "  notebooks/04_matching_and_sensitivity.ipynb"
	@echo "  notebooks/05_finalisation.ipynb"
	@echo "They read from release/frozen_results/ and write to release/figures/."

# ────────────────────────────────────────────────────────────────────────────
# Convenience compound targets
# ────────────────────────────────────────────────────────────────────────────

# Run everything except training (assumes masks already exist)
eval-only: run-baselines benchmark sensitivity

# Full pipeline from raw data (destructive — overwrites existing outputs)
all-from-scratch: build-metadata run-qc optimize-classical run-classical \
                  train-eccount run-eccount run-baselines benchmark sensitivity

# ────────────────────────────────────────────────────────────────────────────
clean:
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -name "*.pyc" -delete 2>/dev/null || true
	find . -name "*.tmp" -delete 2>/dev/null || true
	find . -name "*.tmp.png" -delete 2>/dev/null || true
	@echo "Cleaned."
